#!/usr/bin/env python3
"""
QCM pour les repos restants
"""

import os
import json
from datetime import datetime

TIMESTAMP = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
REPOS_DIR = os.path.join(BASE_DIR, "repos")

REMAINING_QCM = {
    "Javascript.TOR.Workflow": {
        "description": "Visualisations interactives des workflows TOR",
        "questions": [
            {"question": "Qu'est-ce que le routage en oignon ?", "options": ["Chiffrement multi-couches via relais", "Routage direct", "DNS over HTTPS", "VPN simple"], "answer": 0},
            {"question": "Combien de relais Tor utilise-t-il typiquement ?", "options": ["3 (guard, middle, exit)", "2", "5", "1"], "answer": 0},
            {"question": "Qu'est-ce qu'un guard node ?", "options": ["Premier relais, choisi pour la stabilité", "Dernier relais", "Relais central", "Serveur DNS"], "answer": 0},
            {"question": "Qu'est-ce qu'un exit node ?", "options": ["Relais qui contacte la destination finale", "Premier relais", "Relais du milieu", "Serveur d'annuaire"], "answer": 0},
            {"question": "Quel protocole Tor utilise-t-il pour le transport ?", "options": ["TLS sur TCP", "UDP", "QUIC", "DTLS"], "answer": 0},
            {"question": "Comment Tor gère-t-il les clés de chiffrement ?", "options": ["Négociation de clé avec chaque relais", "Clé unique partagée", "Pas de chiffrement", "Clé pre-shared"], "answer": 0},
            {"question": "Qu'est-ce qu'un service onion (.onion) ?", "options": ["Service accessible uniquement via Tor", "Site normal", "CDN", "DNS spécial"], "answer": 0},
            {"question": "Combien de caractères a une adresse .onion v3 ?", "options": ["56", "16", "32", "64"], "answer": 0},
            {"question": "Quel algorithme de chiffrement Tor utilise-t-il ?", "options": ["AES-128-CTR", "DES", "RC4", "3DES"], "answer": 0},
            {"question": "Qu'est-ce que le circuit Tor ?", "options": ["Chemin de relais établi pour la communication", "Câble physique", "Route IP", "Tunnel VPN"], "answer": 0},
            {"question": "Quelle bibliothèque JavaScript anime les visualisations ?", "options": ["D3.js ou Three.js", "jQuery", "React", "Angular"], "answer": 0},
            {"question": "Comment représenter le chiffrement en couches visuellement ?", "options": ["Cercles concentriques ou pelures d'oignon", "Lignes droites", "Carrés", "Points"], "answer": 0},
            {"question": "Qu'est-ce que le hidden service protocol ?", "options": ["Protocole pour services .onion bidirectionnels", "VPN", "Proxy", "Cache"], "answer": 0},
            {"question": "Comment Tor protège-t-il contre l'analyse de trafic ?", "options": ["Taille de cellule fixe, padding", "Compression", "Rien", "Timestamps"], "answer": 0},
            {"question": "Qu'est-ce qu'un Directory Authority ?", "options": ["Serveur qui distribue l'état du réseau", "Serveur DNS", "CDN", "Load balancer"], "answer": 0},
            {"question": "Comment fonctionne le rendezvous point ?", "options": ["Point de rencontre pour services onion", "Serveur central", "Cache", "Proxy"], "answer": 0},
            {"question": "Quelle est la taille d'une cellule Tor ?", "options": ["512 bytes", "1024 bytes", "256 bytes", "4096 bytes"], "answer": 0},
            {"question": "Comment visualiser le flux de données chiffrées ?", "options": ["Animation de paquets à travers les relais", "Texte statique", "Graphique en barres", "Camembert"], "answer": 0},
            {"question": "Qu'est-ce que le consensus Tor ?", "options": ["Document décrivant l'état du réseau", "Accord entre utilisateurs", "Protocole de vote", "Configuration"], "answer": 0},
            {"question": "Combien de clés sont utilisées dans un circuit Tor ?", "options": ["3 (une par relais)", "1", "5", "10"], "answer": 0},
            {"question": "Qu'est-ce que le bridge relay ?", "options": ["Relais non listés pour contourner la censure", "Pont réseau", "Gateway", "Firewall"], "answer": 0},
            {"question": "Comment fonctionne le pluggable transport ?", "options": ["Obfuscation du trafic Tor", "Compression", "Accélération", "Routage"], "answer": 0},
            {"question": "Quelle courbe elliptique Tor utilise-t-il ?", "options": ["Curve25519", "P-256", "secp256k1", "P-384"], "answer": 0},
            {"question": "Comment les introduction points fonctionnent-ils ?", "options": ["Points d'entrée pour contacter un service onion", "Sortie", "Cache", "Backup"], "answer": 0},
            {"question": "Qu'est-ce que Tor Browser ?", "options": ["Firefox modifié pour Tor", "Chrome", "Safari", "Edge"], "answer": 0},
            {"question": "Comment Tor empêche-t-il le fingerprinting ?", "options": ["Configurations standardisées", "VPN", "Proxy", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que NoScript dans Tor Browser ?", "options": ["Extension bloquant JavaScript", "Framework", "API", "Protocole"], "answer": 0},
            {"question": "Comment visualiser la latence du réseau Tor ?", "options": ["Graphiques temps réel des temps de réponse", "Logs texte", "Fichiers", "Email"], "answer": 0},
            {"question": "Qu'est-ce que le stem dans l'écosystème Tor ?", "options": ["Bibliothèque Python pour contrôler Tor", "Navigateur", "Relais", "Service"], "answer": 0},
            {"question": "Comment représenter visuellement l'anonymat ?", "options": ["Masquage progressif de l'identité à travers les relais", "Couleurs", "Tailles", "Formes"], "answer": 0}
        ]
    },
    "Python.AccessForbiddenFiles": {
        "description": "Scanner de fichiers sensibles exposés",
        "questions": [
            {"question": "Quels fichiers sensibles sont couramment recherchés ?", "options": [".env, .git, backups, config.php", "images", "css", "html"], "answer": 0},
            {"question": "Pourquoi le fichier .env est-il sensible ?", "options": ["Contient des credentials et secrets", "Code source", "Styles", "Images"], "answer": 0},
            {"question": "Comment détecter un dossier .git exposé ?", "options": ["Requête vers /.git/config", "DNS lookup", "WHOIS", "Traceroute"], "answer": 0},
            {"question": "Quel status HTTP indique un fichier trouvé ?", "options": ["200 OK", "404", "500", "301"], "answer": 0},
            {"question": "Quels fichiers de backup sont recherchés ?", "options": ["*.bak, *.old, *.backup, ~", "*.txt", "*.md", "*.html"], "answer": 0},
            {"question": "Comment exploiter un .git exposé ?", "options": ["git-dumper pour reconstruire le repo", "wget", "curl", "ftp"], "answer": 0},
            {"question": "Quels fichiers de configuration sont ciblés ?", "options": ["wp-config.php, config.ini, settings.py", "index.html", "style.css", "app.js"], "answer": 0},
            {"question": "Comment scanner plusieurs chemins en parallèle ?", "options": ["ThreadPoolExecutor ou asyncio", "Boucle séquentielle", "Manuel", "Pas possible"], "answer": 0},
            {"question": "Quel header indique un serveur Apache ?", "options": ["Server: Apache", "X-Server", "Via", "Host"], "answer": 0},
            {"question": "Comment détecter les fichiers de logs exposés ?", "options": ["Requêtes vers /logs/, /var/log/", "DNS", "WHOIS", "Ping"], "answer": 0},
            {"question": "Quels fichiers IDE sont parfois exposés ?", "options": [".idea/, .vscode/, .project", ".git seulement", "Aucun", "Tous"], "answer": 0},
            {"question": "Comment le scanner gère-t-il les redirections ?", "options": ["Suivre ou ignorer selon configuration", "Toujours suivre", "Jamais suivre", "Erreur"], "answer": 0},
            {"question": "Quel fichier révèle la structure du projet ?", "options": ["composer.json, package.json", "index.html", "favicon.ico", "robots.txt"], "answer": 0},
            {"question": "Comment éviter la détection par WAF ?", "options": ["Rate limiting, User-Agent rotation", "Aucune technique", "Attaque rapide", "Proxy simple"], "answer": 0},
            {"question": "Quels fichiers de base de données sont recherchés ?", "options": [".sql, .sqlite, .db, dump.*", ".html", ".css", ".js"], "answer": 0},
            {"question": "Comment valider qu'un fichier contient des secrets ?", "options": ["Parser le contenu et chercher des patterns", "Taille du fichier", "Extension seule", "Nom du fichier"], "answer": 0},
            {"question": "Quels secrets sont typiquement dans .env ?", "options": ["API keys, DB passwords, secrets", "HTML", "CSS", "Images"], "answer": 0},
            {"question": "Comment scanner des sous-domaines ?", "options": ["Énumération DNS + scan de chaque sous-domaine", "Scan IP uniquement", "WHOIS", "Ping"], "answer": 0},
            {"question": "Quel outil automatise ce type de scan ?", "options": ["Dirsearch, Gobuster, ffuf", "Nmap", "Wireshark", "tcpdump"], "answer": 0},
            {"question": "Comment générer une wordlist de fichiers ?", "options": ["SecLists, création personnalisée", "Aléatoire", "Manuel", "API"], "answer": 0},
            {"question": "Quels fichiers PHP de debug existent ?", "options": ["phpinfo.php, test.php, debug.php", "index.php", "config.php", "admin.php"], "answer": 0},
            {"question": "Comment détecter les archives exposées ?", "options": ["Rechercher .zip, .tar.gz, .rar", "DNS", "WHOIS", "Ping"], "answer": 0},
            {"question": "Quel fichier révèle les dépendances Node.js ?", "options": ["package.json, package-lock.json", "index.js", "app.js", "server.js"], "answer": 0},
            {"question": "Comment exploiter un fichier de config exposé ?", "options": ["Extraire credentials et accéder aux services", "Rien", "Rapport seul", "Ignorer"], "answer": 0},
            {"question": "Quels fichiers WordPress sont sensibles ?", "options": ["wp-config.php, .htaccess, xmlrpc.php", "index.php", "style.css", "header.php"], "answer": 0},
            {"question": "Comment le scanner gère-t-il les timeouts ?", "options": ["Retry avec backoff ou skip", "Abandon total", "Attente infinie", "Erreur"], "answer": 0},
            {"question": "Quels fichiers de versioning sont exposés ?", "options": [".svn, .hg, .bzr en plus de .git", "Aucun", "Tous", ".git seul"], "answer": 0},
            {"question": "Comment prioriser les résultats ?", "options": ["Scoring par criticité du fichier", "Ordre alphabétique", "Aléatoire", "Premier trouvé"], "answer": 0},
            {"question": "Quel format de rapport est généré ?", "options": ["JSON, HTML, CSV", "Texte seul", "PDF", "Word"], "answer": 0},
            {"question": "Comment éviter les faux positifs ?", "options": ["Vérifier le contenu, pas seulement le status", "Ignorer 200", "Accepter tous", "Filtrer par taille"], "answer": 0}
        ]
    },
    "Python.Apache.Logs": {
        "description": "Analyseur de logs Apache avec ML",
        "questions": [
            {"question": "Quel algorithme de clustering est utilisé ?", "options": ["K-Means et DBSCAN", "SVM", "Neural Network", "Random Forest"], "answer": 0},
            {"question": "Quel format de log Apache est analysé ?", "options": ["Combined ou Common Log Format", "JSON", "XML", "Binary"], "answer": 0},
            {"question": "Quels patterns d'attaque sont détectés ?", "options": ["SQLi, XSS, Path Traversal, Scanners", "Aucun", "DDoS seul", "Spam"], "answer": 0},
            {"question": "Comment K-Means fonctionne-t-il ?", "options": ["Groupement par centroïdes", "Arbre de décision", "Régression", "Classification"], "answer": 0},
            {"question": "Quel avantage DBSCAN a-t-il sur K-Means ?", "options": ["Détection de clusters de forme arbitraire", "Plus rapide", "Plus simple", "Moins de mémoire"], "answer": 0},
            {"question": "Quelles features sont extraites des logs ?", "options": ["IP, User-Agent, URL, Status, Taille", "Aucune", "Texte brut", "Binary"], "answer": 0},
            {"question": "Comment détecter un scan de vulnérabilités ?", "options": ["Rafales de requêtes vers chemins suspects", "IP unique", "User-Agent", "Referer"], "answer": 0},
            {"question": "Quel User-Agent indique souvent un scanner ?", "options": ["Nikto, sqlmap, Nmap, w3af", "Chrome", "Firefox", "Safari"], "answer": 0},
            {"question": "Comment normaliser les données pour ML ?", "options": ["StandardScaler, MinMaxScaler", "Pas de normalisation", "Log", "Sqrt"], "answer": 0},
            {"question": "Quelle bibliothèque Python fait le ML ?", "options": ["scikit-learn", "TensorFlow", "PyTorch", "Keras"], "answer": 0},
            {"question": "Comment visualiser les clusters ?", "options": ["Matplotlib, Seaborn, PCA", "Texte", "HTML", "PDF"], "answer": 0},
            {"question": "Qu'est-ce que PCA dans ce contexte ?", "options": ["Réduction de dimensions pour visualisation", "Analyse", "Parsing", "Clustering"], "answer": 0},
            {"question": "Comment identifier les anomalies ?", "options": ["Points éloignés des centroïdes / outliers DBSCAN", "Manuellement", "Aléatoire", "Premier point"], "answer": 0},
            {"question": "Quels champs du log contiennent l'URL ?", "options": ["request / request_uri", "ip", "status", "size"], "answer": 0},
            {"question": "Comment détecter une attaque de force brute ?", "options": ["Nombreuses requêtes 401/403 depuis une IP", "200 OK", "Redirection", "Timeout"], "answer": 0},
            {"question": "Quel status HTTP indique une tentative bloquée ?", "options": ["403 Forbidden", "200 OK", "301", "500"], "answer": 0},
            {"question": "Comment parser les logs Apache en Python ?", "options": ["Regex ou apache-log-parser", "JSON.parse", "XML parser", "Binary reader"], "answer": 0},
            {"question": "Qu'est-ce que le 'silhouette score' ?", "options": ["Mesure de qualité du clustering", "Score de sécurité", "Métrique de performance", "Index de log"], "answer": 0},
            {"question": "Comment détecter les requêtes SQL injection ?", "options": ["Patterns SELECT, UNION, --, OR 1=1", "GET simple", "POST vide", "HEAD"], "answer": 0},
            {"question": "Quelles IPs sont généralement malveillantes ?", "options": ["Celles dans les clusters d'attaque", "Toutes", "Aucune", "Locales"], "answer": 0},
            {"question": "Comment enrichir les données avec GeoIP ?", "options": ["Ajouter pays/ville par IP", "DNS", "WHOIS", "Ping"], "answer": 0},
            {"question": "Quelle bibliothèque fait le GeoIP ?", "options": ["geoip2, maxminddb", "requests", "socket", "dns"], "answer": 0},
            {"question": "Comment détecter les path traversal ?", "options": ["Patterns ../, %2e%2e/", "Extensions", "Taille", "Status"], "answer": 0},
            {"question": "Qu'est-ce qu'un bot crawler légitime ?", "options": ["Googlebot, Bingbot", "sqlmap", "Nikto", "w3af"], "answer": 0},
            {"question": "Comment différencier bot légitime et malveillant ?", "options": ["User-Agent + comportement + reverse DNS", "IP seule", "Aléatoire", "Timestamp"], "answer": 0},
            {"question": "Quelle fréquence de requêtes est suspecte ?", "options": [">10 req/sec depuis une IP", "1 req/min", "1 req/heure", "1 req/jour"], "answer": 0},
            {"question": "Comment stocker les résultats d'analyse ?", "options": ["JSON, CSV, Base de données", "Papier", "Email", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que le 'elbow method' ?", "options": ["Méthode pour choisir k dans K-Means", "Technique de parsing", "Format de log", "Algorithme"], "answer": 0},
            {"question": "Comment alerter sur les attaques détectées ?", "options": ["Email, Slack, SIEM", "Rien", "Log seul", "Console"], "answer": 0},
            {"question": "Quelle est la complexité de K-Means ?", "options": ["O(n*k*i) - n points, k clusters, i iterations", "O(n)", "O(1)", "O(n²)"], "answer": 0}
        ]
    },
    "Python.Arping": {
        "description": "Scanner réseau ARP avec Scapy",
        "questions": [
            {"question": "Que fait le protocole ARP ?", "options": ["Résolution IP vers MAC", "Résolution MAC vers IP", "Routage", "DNS"], "answer": 0},
            {"question": "Quelle couche OSI utilise ARP ?", "options": ["Couche 2 (Liaison)", "Couche 3 (Réseau)", "Couche 4 (Transport)", "Couche 7 (Application)"], "answer": 0},
            {"question": "Comment créer un paquet ARP avec Scapy ?", "options": ["Ether()/ARP()", "ARP()", "IP()/ARP()", "TCP()/ARP()"], "answer": 0},
            {"question": "Quelle adresse MAC broadcast est utilisée ?", "options": ["ff:ff:ff:ff:ff:ff", "00:00:00:00:00:00", "11:11:11:11:11:11", "aa:aa:aa:aa:aa:aa"], "answer": 0},
            {"question": "Comment envoyer un ARP request ?", "options": ["srp() avec Ether/ARP", "send()", "sr()", "transmit()"], "answer": 0},
            {"question": "Qu'est-ce que l'ARP spoofing ?", "options": ["Fausse réponse ARP pour intercepter le trafic", "Scan ARP", "Découverte réseau", "DNS poisoning"], "answer": 0},
            {"question": "Comment détecter les machines sur un réseau local ?", "options": ["ARP scan sur la plage IP", "DNS lookup", "WHOIS", "Traceroute"], "answer": 0},
            {"question": "Quel champ ARP contient l'IP recherchée ?", "options": ["pdst (protocol destination)", "psrc", "hwdst", "hwsrc"], "answer": 0},
            {"question": "Comment scanner un subnet /24 ?", "options": ["Boucle sur 254 IPs avec ARP request", "Ping broadcast", "DNS zone transfer", "SNMP walk"], "answer": 0},
            {"question": "Quelle est la différence entre sr() et srp() ?", "options": ["srp() opère au niveau 2 (Ethernet)", "Aucune", "sr() est plus rapide", "srp() est deprecated"], "answer": 0},
            {"question": "Comment obtenir l'adresse MAC depuis une réponse ARP ?", "options": ["response[ARP].hwsrc", "response.mac", "response.ethernet", "response.hardware"], "answer": 0},
            {"question": "Pourquoi les privilèges root sont-ils nécessaires ?", "options": ["Accès aux raw sockets", "Écriture fichiers", "Réseau", "Configuration"], "answer": 0},
            {"question": "Quelle bibliothèque gère les adresses réseau ?", "options": ["ipaddress ou netaddr", "socket", "struct", "array"], "answer": 0},
            {"question": "Comment gérer les timeouts ARP ?", "options": ["Paramètre timeout dans srp()", "Try/except", "While loop", "Retry manuel"], "answer": 0},
            {"question": "Qu'est-ce que l'ARP cache ?", "options": ["Table de correspondances IP-MAC", "Cache DNS", "Cache web", "Buffer réseau"], "answer": 0},
            {"question": "Comment afficher l'ARP cache système ?", "options": ["arp -a ou ip neigh", "netstat", "ifconfig", "route"], "answer": 0},
            {"question": "Quel outil CLI fait de l'arping ?", "options": ["arping", "ping", "traceroute", "nmap"], "answer": 0},
            {"question": "Comment identifier le fabricant depuis une MAC ?", "options": ["OUI lookup (premiers 3 octets)", "DNS", "WHOIS", "Ping"], "answer": 0},
            {"question": "Qu'est-ce que le GARP (Gratuitous ARP) ?", "options": ["ARP annonçant sa propre IP (failover, etc.)", "ARP request", "ARP reply", "ARP probe"], "answer": 0},
            {"question": "Comment se protéger contre l'ARP spoofing ?", "options": ["ARP statique, DAI, 802.1X", "Firewall", "Antivirus", "VPN"], "answer": 0},
            {"question": "Quel est le format d'une adresse MAC ?", "options": ["XX:XX:XX:XX:XX:XX (6 octets hex)", "IP format", "8 octets", "4 octets"], "answer": 0},
            {"question": "Comment Scapy représente les réponses multiples ?", "options": ["Liste de tuples (sent, received)", "Dictionnaire", "String", "Integer"], "answer": 0},
            {"question": "Quelle option Scapy désactive la verbosité ?", "options": ["verbose=0 ou conf.verb=0", "quiet=True", "silent=True", "no_output=True"], "answer": 0},
            {"question": "Comment filtrer les réponses dans srp() ?", "options": ["Paramètre filter ou analyse post-réception", "Pre-filter", "Regex", "Lambda"], "answer": 0},
            {"question": "Qu'est-ce que le DAI (Dynamic ARP Inspection) ?", "options": ["Protection switch contre ARP spoofing", "Protocole", "Outil", "Service"], "answer": 0},
            {"question": "Comment optimiser le scan de grands réseaux ?", "options": ["Threading, réduction timeout, batching", "Séquentiel", "Un par un", "Lentement"], "answer": 0},
            {"question": "Quelle interface Scapy utilise par défaut ?", "options": ["conf.iface (interface par défaut)", "eth0 toujours", "wlan0", "lo"], "answer": 0},
            {"question": "Comment spécifier une interface dans srp() ?", "options": ["iface='eth0'", "interface='eth0'", "dev='eth0'", "nic='eth0'"], "answer": 0},
            {"question": "Qu'est-ce que le ARP probe ?", "options": ["ARP pour vérifier si une IP est utilisée", "ARP normal", "ARP reply", "ARP gratuit"], "answer": 0},
            {"question": "Comment formater la sortie du scan ?", "options": ["Tableau avec IP et MAC", "JSON", "XML", "Binaire"], "answer": 0}
        ]
    },
    "Python.CORS.Handler": {
        "description": "Lab de test CORS avec Flask",
        "questions": [
            {"question": "Que signifie CORS ?", "options": ["Cross-Origin Resource Sharing", "Cross-Origin Request Security", "Client Origin Resource System", "Cross-Origin Response Service"], "answer": 0},
            {"question": "Quel header permet les requêtes cross-origin ?", "options": ["Access-Control-Allow-Origin", "Allow-Origin", "X-Origin", "Cross-Origin"], "answer": 0},
            {"question": "Quelle valeur ACAO autorise tout ?", "options": ["* (wildcard)", "all", "any", "true"], "answer": 0},
            {"question": "Qu'est-ce qu'une requête preflight ?", "options": ["OPTIONS avant la vraie requête", "GET initial", "POST test", "HEAD check"], "answer": 0},
            {"question": "Quand le preflight est-il déclenché ?", "options": ["Méthodes non-simple ou headers custom", "Toujours", "Jamais", "GET uniquement"], "answer": 0},
            {"question": "Quels sont les méthodes simples CORS ?", "options": ["GET, HEAD, POST (limité)", "Toutes", "GET seul", "POST seul"], "answer": 0},
            {"question": "Quel header liste les méthodes autorisées ?", "options": ["Access-Control-Allow-Methods", "Allow-Methods", "Methods", "X-Methods"], "answer": 0},
            {"question": "Comment autoriser les credentials cross-origin ?", "options": ["Access-Control-Allow-Credentials: true", "Credentials: allow", "X-Credentials", "Allow-Cookies"], "answer": 0},
            {"question": "Pourquoi * ne fonctionne pas avec credentials ?", "options": ["Sécurité : origin explicite requise", "Bug", "Performance", "Standard"], "answer": 0},
            {"question": "Quel framework Python est utilisé ?", "options": ["Flask", "Django", "FastAPI", "Tornado"], "answer": 0},
            {"question": "Comment activer CORS dans Flask ?", "options": ["flask-cors ou headers manuels", "Automatique", "Middleware", "Extension"], "answer": 0},
            {"question": "Qu'est-ce que le header Origin ?", "options": ["Origine de la requête (scheme://host:port)", "User-Agent", "Referer", "Host"], "answer": 0},
            {"question": "Comment tester CORS depuis le navigateur ?", "options": ["fetch() cross-origin et observer console", "curl", "wget", "telnet"], "answer": 0},
            {"question": "Quelle erreur indique un problème CORS ?", "options": ["CORS policy blocked", "404", "500", "Timeout"], "answer": 0},
            {"question": "Quel header expose des headers custom ?", "options": ["Access-Control-Expose-Headers", "Expose-Headers", "X-Headers", "Show-Headers"], "answer": 0},
            {"question": "Combien de temps le preflight est-il cacheable ?", "options": ["Access-Control-Max-Age (secondes)", "Toujours", "Jamais", "1 heure fixe"], "answer": 0},
            {"question": "Comment restreindre CORS à un domaine ?", "options": ["ACAO: https://example.com", "ACAO: *", "X-Domain", "Restrict-Origin"], "answer": 0},
            {"question": "Quels risques si CORS mal configuré ?", "options": ["Data exfiltration, CSRF facilité", "Lenteur", "Crash", "Rien"], "answer": 0},
            {"question": "Comment logger les requêtes CORS ?", "options": ["Middleware Flask ou logging", "Console", "Fichier", "Email"], "answer": 0},
            {"question": "Qu'est-ce que le null origin ?", "options": ["Origin de fichiers locaux ou sandboxed iframes", "Absence d'origin", "Erreur", "Default"], "answer": 0},
            {"question": "Pourquoi ne pas autoriser null origin ?", "options": ["Exploitable pour bypass", "Sécurisé", "Standard", "Performance"], "answer": 0},
            {"question": "Comment tester avec curl ?", "options": ["-H 'Origin: http://evil.com'", "--cors", "-X CORS", "--preflight"], "answer": 0},
            {"question": "Quel header indique les headers autorisés ?", "options": ["Access-Control-Allow-Headers", "Allow-Headers", "X-Headers", "Permit-Headers"], "answer": 0},
            {"question": "Comment le navigateur gère-t-il le preflight ?", "options": ["Automatiquement avant la requête", "Manuellement", "Jamais", "Plugin"], "answer": 0},
            {"question": "Qu'est-ce qu'une simple request CORS ?", "options": ["GET/HEAD/POST avec headers standard", "Toute requête", "PUT/DELETE", "OPTIONS"], "answer": 0},
            {"question": "Comment implémenter CORS dynamique ?", "options": ["Valider Origin contre whitelist", "Toujours *", "Refuser tout", "Hardcode"], "answer": 0},
            {"question": "Quel est le status du preflight réussi ?", "options": ["204 No Content ou 200 OK", "201", "301", "404"], "answer": 0},
            {"question": "Comment désactiver CORS pour le dev ?", "options": ["Extension navigateur ou proxy", "Modifier le navigateur", "Recompiler", "Pas possible"], "answer": 0},
            {"question": "Qu'est-ce que le CORB ?", "options": ["Cross-Origin Read Blocking (Chrome)", "CORS Block", "Origin Block", "Request Block"], "answer": 0},
            {"question": "Comment sécuriser CORS en production ?", "options": ["Whitelist stricte, pas de wildcard avec credentials", "Wildcard", "Tout autoriser", "Désactiver"], "answer": 0}
        ]
    },
    "Python.Dome.SubDomains": {
        "description": "Énumération de sous-domaines",
        "questions": [
            {"question": "Qu'est-ce que l'énumération de sous-domaines ?", "options": ["Découvrir tous les sous-domaines d'un domaine", "Créer des sous-domaines", "Supprimer des sous-domaines", "Configurer DNS"], "answer": 0},
            {"question": "Quelle technique utilise des wordlists ?", "options": ["Bruteforce DNS", "Zone transfer", "Certificate Transparency", "WHOIS"], "answer": 0},
            {"question": "Qu'est-ce que le Certificate Transparency ?", "options": ["Logs publics de certificats SSL", "Chiffrement", "TLS", "HTTPS"], "answer": 0},
            {"question": "Quel service expose les logs CT ?", "options": ["crt.sh, censys", "WHOIS", "DNS", "BGP"], "answer": 0},
            {"question": "Comment fonctionne le bruteforce DNS ?", "options": ["Résoudre sub.domain.com pour chaque mot", "Deviner les IPs", "Scanner les ports", "Ping"], "answer": 0},
            {"question": "Quel type de record DNS résout les noms ?", "options": ["A et AAAA", "MX", "TXT", "SOA"], "answer": 0},
            {"question": "Qu'est-ce qu'un wildcard DNS ?", "options": ["*.domain.com résout vers une IP", "DNS cache", "Round robin", "Load balancer"], "answer": 0},
            {"question": "Comment détecter un wildcard ?", "options": ["Tester un sous-domaine aléatoire inexistant", "Ping", "Traceroute", "WHOIS"], "answer": 0},
            {"question": "Quelle API donne des sous-domaines ?", "options": ["VirusTotal, SecurityTrails, Shodan", "Google", "Bing", "Yahoo"], "answer": 0},
            {"question": "Comment faire une résolution DNS récursive ?", "options": ["Suivre les CNAME jusqu'à l'IP finale", "Une seule requête", "Cache local", "Fichier hosts"], "answer": 0},
            {"question": "Quel outil CLI fait de l'énumération ?", "options": ["Sublist3r, Amass, Subfinder", "Nmap", "Wireshark", "tcpdump"], "answer": 0},
            {"question": "Comment paralléliser les requêtes DNS ?", "options": ["asyncio / threading", "Séquentiel", "Un par un", "Manuel"], "answer": 0},
            {"question": "Quel module Python fait les requêtes DNS ?", "options": ["dnspython", "socket", "requests", "urllib"], "answer": 0},
            {"question": "Comment éviter le rate limiting DNS ?", "options": ["Délais, serveurs DNS multiples", "Requêtes rapides", "Ignorer", "VPN"], "answer": 0},
            {"question": "Qu'est-ce qu'un DNS zone transfer ?", "options": ["AXFR - copie de la zone DNS", "Query normale", "Update DNS", "Delete zone"], "answer": 0},
            {"question": "Pourquoi le zone transfer est-il rarement possible ?", "options": ["Désactivé pour sécurité", "Trop lent", "Trop complexe", "Obsolète"], "answer": 0},
            {"question": "Comment tester un zone transfer ?", "options": ["dig axfr domain.com @ns.domain.com", "nslookup", "ping", "traceroute"], "answer": 0},
            {"question": "Quelle information révèle un sous-domaine ?", "options": ["Services, environnements, structure interne", "Rien", "Mot de passe", "Code source"], "answer": 0},
            {"question": "Comment filtrer les résultats wildcard ?", "options": ["Comparer avec réponse de référence", "Garder tous", "Supprimer tous", "Aléatoire"], "answer": 0},
            {"question": "Quel format de sortie est courant ?", "options": ["JSON, CSV, texte", "XML", "PDF", "Word"], "answer": 0},
            {"question": "Comment valider qu'un sous-domaine est actif ?", "options": ["HTTP request vers le sous-domaine", "DNS seul", "Ping seul", "WHOIS"], "answer": 0},
            {"question": "Qu'est-ce que le subdomain takeover ?", "options": ["Récupérer un sous-domaine abandonné", "Hacking DNS", "Zone transfer", "DNS cache poisoning"], "answer": 0},
            {"question": "Quels services sont vulnérables au takeover ?", "options": ["S3, GitHub Pages, Heroku", "Google", "Cloudflare", "AWS"], "answer": 0},
            {"question": "Comment détecter un takeover potentiel ?", "options": ["CNAME vers service avec fingerprint", "A record", "MX record", "TXT record"], "answer": 0},
            {"question": "Quelle wordlist est recommandée ?", "options": ["SecLists dns subdomain wordlists", "Rockyou", "Common passwords", "Top 100"], "answer": 0},
            {"question": "Comment combiner plusieurs sources ?", "options": ["Merge et deduplicate les résultats", "Une seule source", "Aléatoire", "Manuel"], "answer": 0},
            {"question": "Qu'est-ce que la permutation de sous-domaines ?", "options": ["Générer des variations (dev-, -dev, dev1)", "Copier", "Supprimer", "Renommer"], "answer": 0},
            {"question": "Comment gérer les sous-domaines internationaux ?", "options": ["Punycode encoding", "UTF-8", "ASCII", "Base64"], "answer": 0},
            {"question": "Quel est l'intérêt pour le bug bounty ?", "options": ["Élargir la surface d'attaque", "Aucun", "Réduire le scope", "Documentation"], "answer": 0},
            {"question": "Comment automatiser l'énumération régulière ?", "options": ["Cron job + stockage des résultats", "Manuel", "Email", "SMS"], "answer": 0}
        ]
    },
    "Python.Network.Connections": {
        "description": "Monitoring des connexions réseau",
        "questions": [
            {"question": "Quel module Python liste les connexions ?", "options": ["psutil", "socket", "os", "sys"], "answer": 0},
            {"question": "Comment obtenir les connexions actives ?", "options": ["psutil.net_connections()", "socket.getconnections()", "os.connections()", "netstat()"], "answer": 0},
            {"question": "Quels états TCP existent ?", "options": ["ESTABLISHED, LISTEN, TIME_WAIT, CLOSE_WAIT...", "OPEN, CLOSE", "UP, DOWN", "ON, OFF"], "answer": 0},
            {"question": "Comment identifier le processus d'une connexion ?", "options": ["PID dans la connexion + psutil.Process()", "Nom seul", "Impossible", "Fichier"], "answer": 0},
            {"question": "Quel outil CLI montre les connexions ?", "options": ["netstat, ss", "ps", "top", "ifconfig"], "answer": 0},
            {"question": "Comment filtrer les connexions ESTABLISHED ?", "options": ["conn.status == 'ESTABLISHED'", "conn.state", "conn.active", "conn.open"], "answer": 0},
            {"question": "Quelles informations une connexion contient-elle ?", "options": ["Local/remote addr, port, status, pid", "Nom seul", "IP seule", "Port seul"], "answer": 0},
            {"question": "Comment surveiller en temps réel ?", "options": ["Boucle avec sleep et refresh", "Une fois", "Manuel", "Fichier"], "answer": 0},
            {"question": "Quel port indique une connexion web ?", "options": ["80, 443", "22", "25", "53"], "answer": 0},
            {"question": "Comment détecter les connexions suspectes ?", "options": ["Ports/IPs inhabituels, processus inconnus", "Tout est suspect", "Rien", "Taille"], "answer": 0},
            {"question": "Qu'est-ce qu'une connexion LISTEN ?", "options": ["Serveur attendant des connexions", "Client connecté", "Erreur", "Fermé"], "answer": 0},
            {"question": "Comment obtenir le nom du processus ?", "options": ["psutil.Process(pid).name()", "os.getname()", "sys.process()", "proc.name"], "answer": 0},
            {"question": "Quels protocoles sont listés ?", "options": ["TCP, UDP", "HTTP", "FTP", "SSH"], "answer": 0},
            {"question": "Comment afficher en tableau formaté ?", "options": ["tabulate, prettytable", "print()", "Texte brut", "JSON"], "answer": 0},
            {"question": "Qu'est-ce que TIME_WAIT ?", "options": ["Connexion fermée, attente de cleanup", "Active", "Erreur", "Timeout"], "answer": 0},
            {"question": "Comment détecter les reverse shells ?", "options": ["Connexions sortantes vers ports suspects", "Connexions entrantes", "LISTEN", "UDP"], "answer": 0},
            {"question": "Quel état indique une connexion entrante ?", "options": ["ESTABLISHED vers un port LISTEN local", "TIME_WAIT", "CLOSE_WAIT", "SYN_SENT"], "answer": 0},
            {"question": "Comment exporter les résultats ?", "options": ["JSON, CSV, log file", "Papier", "Email", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que SYN_SENT ?", "options": ["Tentative de connexion en cours", "Connecté", "Fermé", "Erreur"], "answer": 0},
            {"question": "Comment identifier une attaque de type C2 ?", "options": ["Connexions régulières vers IPs/ports suspects", "Trafic web normal", "DNS", "DHCP"], "answer": 0},
            {"question": "Quel outil graphique visualise les connexions ?", "options": ["Netdata, Grafana", "Word", "Excel", "PowerPoint"], "answer": 0},
            {"question": "Comment corréler avec les IOCs ?", "options": ["Comparer IPs/domains avec listes de menaces", "Ignorer", "Tout bloquer", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que le CLOSE_WAIT ?", "options": ["Attente fermeture côté application", "Ouvert", "Actif", "Timeout"], "answer": 0},
            {"question": "Comment surveiller une interface spécifique ?", "options": ["Filtrer par adresse locale", "Toutes", "Aucune", "Aléatoire"], "answer": 0},
            {"question": "Quel privilège est requis pour voir tous les PIDs ?", "options": ["Root/Admin", "User normal", "Guest", "Aucun"], "answer": 0},
            {"question": "Comment détecter le port scanning ?", "options": ["Nombreuses connexions SYN_RECV", "ESTABLISHED", "LISTEN", "CLOSE"], "answer": 0},
            {"question": "Qu'est-ce que FIN_WAIT ?", "options": ["Fermeture initiée, attente confirmation", "Ouvert", "Actif", "Erreur"], "answer": 0},
            {"question": "Comment alerter sur anomalies ?", "options": ["Seuils + notifications", "Log seul", "Rien", "Rapport"], "answer": 0},
            {"question": "Quel delta montre de nouvelles connexions ?", "options": ["Comparer snapshots successifs", "Une mesure", "Historique", "Cache"], "answer": 0},
            {"question": "Comment intégrer avec un SIEM ?", "options": ["Envoyer logs en syslog/JSON", "Email", "SMS", "Papier"], "answer": 0}
        ]
    },
    "Python.Nmap.Batch": {
        "description": "Scans réseau batch avec dashboard",
        "questions": [
            {"question": "Quels outils de scan sont intégrés ?", "options": ["Nmap, Masscan, Netcat, Hping3", "Nmap seul", "Ping", "Traceroute"], "answer": 0},
            {"question": "Quel framework web affiche le dashboard ?", "options": ["Flask", "Django", "FastAPI", "Bottle"], "answer": 0},
            {"question": "Qu'est-ce que SSE dans ce contexte ?", "options": ["Server-Sent Events pour temps réel", "SSL", "Session", "Security"], "answer": 0},
            {"question": "Comment paralléliser les scans ?", "options": ["Multi-threading", "Séquentiel", "Un par un", "Queue"], "answer": 0},
            {"question": "Quel avantage Masscan sur Nmap ?", "options": ["Vitesse (millions de paquets/sec)", "Précision", "Simplicité", "Compatibilité"], "answer": 0},
            {"question": "Comment lancer un scan Nmap via Python ?", "options": ["subprocess ou python-nmap", "os.system() seul", "exec()", "eval()"], "answer": 0},
            {"question": "Qu'est-ce que le mode batch ?", "options": ["Exécution de plusieurs scans automatiquement", "Un seul scan", "Manuel", "Interactif"], "answer": 0},
            {"question": "Comment stocker les résultats ?", "options": ["Base de données ou fichiers JSON/XML", "Mémoire seule", "Papier", "Email"], "answer": 0},
            {"question": "Quel format Nmap export-t-il ?", "options": ["XML, JSON, grepable", "PDF", "Word", "HTML seul"], "answer": 0},
            {"question": "Comment planifier des scans récurrents ?", "options": ["Cron ou scheduler Python", "Manuel", "Email", "SMS"], "answer": 0},
            {"question": "Qu'est-ce que Netcat dans ce contexte ?", "options": ["Test de connectivité port", "Scanner", "Proxy", "Firewall"], "answer": 0},
            {"question": "Comment Hping3 est-il utilisé ?", "options": ["Craft de paquets personnalisés", "Scan simple", "DNS", "DHCP"], "answer": 0},
            {"question": "Quel pattern SSE envoie les updates ?", "options": ["data: {json}\\n\\n", "JSON direct", "XML", "Binary"], "answer": 0},
            {"question": "Comment gérer les erreurs de scan ?", "options": ["Try/except avec logging", "Ignorer", "Crash", "Retry infini"], "answer": 0},
            {"question": "Quel module Python gère les threads ?", "options": ["threading ou concurrent.futures", "asyncio seul", "multiprocessing seul", "os"], "answer": 0},
            {"question": "Comment limiter les scans concurrents ?", "options": ["ThreadPoolExecutor(max_workers)", "Illimité", "Un seul", "Aléatoire"], "answer": 0},
            {"question": "Qu'est-ce que le rate limiting dans Nmap ?", "options": ["Limiter les paquets/seconde", "Bloquer les scans", "Cache", "Buffer"], "answer": 0},
            {"question": "Comment parser la sortie XML Nmap ?", "options": ["xml.etree ou python-nmap", "Regex", "Split", "Manual"], "answer": 0},
            {"question": "Quel endpoint Flask sert le dashboard ?", "options": ["/ ou /dashboard", "/api", "/scan", "/results"], "answer": 0},
            {"question": "Comment notifier la fin d'un scan ?", "options": ["SSE, webhook, email", "Attendre", "Polling", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que le scan de vulnérabilités Nmap ?", "options": ["Scripts NSE vuln", "Scan port seul", "Ping", "DNS"], "answer": 0},
            {"question": "Comment sécuriser le dashboard ?", "options": ["Authentification, HTTPS, firewall", "Rien", "Public", "Password simple"], "answer": 0},
            {"question": "Quel format d'affichage est utilisé ?", "options": ["HTML avec JavaScript", "Console", "PDF", "Word"], "answer": 0},
            {"question": "Comment comparer des scans ?", "options": ["Diff des résultats", "Manuel", "Visual", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que le scan de découverte ?", "options": ["Identifier les hôtes actifs", "Vulnérabilités", "Services", "Versions"], "answer": 0},
            {"question": "Comment gérer les grands réseaux ?", "options": ["Segmentation, parallélisation", "Tout en une fois", "Ignorer", "Manuel"], "answer": 0},
            {"question": "Quel est l'avantage du dashboard web ?", "options": ["Visualisation et suivi en temps réel", "Plus rapide", "Plus précis", "Plus sécurisé"], "answer": 0},
            {"question": "Comment exporter les rapports ?", "options": ["PDF, HTML, JSON, CSV", "Texte seul", "Image", "Vidéo"], "answer": 0},
            {"question": "Qu'est-ce que le fingerprinting de services ?", "options": ["Identifier versions et applications", "Ports seuls", "IPs", "MACs"], "answer": 0},
            {"question": "Comment intégrer avec un SIEM ?", "options": ["Export syslog ou API", "Email", "SMS", "Papier"], "answer": 0}
        ]
    },
    "Python.PHP.Sec.Scan": {
        "description": "Scanner de sécurité PHP par analyse statique",
        "questions": [
            {"question": "Qu'est-ce que l'analyse statique ?", "options": ["Analyse du code sans exécution", "Exécution du code", "Test manuel", "Fuzzing"], "answer": 0},
            {"question": "Qu'est-ce que le taint tracking ?", "options": ["Suivre les données utilisateur jusqu'aux sinks", "Chiffrement", "Compression", "Cache"], "answer": 0},
            {"question": "Qu'est-ce qu'un sink en sécurité ?", "options": ["Fonction dangereuse (exec, query, echo)", "Source de données", "Cache", "Buffer"], "answer": 0},
            {"question": "Qu'est-ce qu'une source de données ?", "options": ["Entrée utilisateur ($_GET, $_POST)", "Fonction", "Variable locale", "Constante"], "answer": 0},
            {"question": "Quel parser PHP est utilisé ?", "options": ["tree-sitter", "php-parser", "nikic/php-parser", "custom"], "answer": 0},
            {"question": "Combien de types de vulnérabilités sont détectées ?", "options": ["16+", "5", "3", "10"], "answer": 0},
            {"question": "Quel format de rapport est généré ?", "options": ["SARIF, HTML", "PDF", "Word", "Excel"], "answer": 0},
            {"question": "Combien de tests unitaires existent ?", "options": ["89+", "10", "50", "200"], "answer": 0},
            {"question": "Qu'est-ce que SARIF ?", "options": ["Static Analysis Results Interchange Format", "Security Analysis Report", "Scan Results File", "Security Archive"], "answer": 0},
            {"question": "Quelles vulnérabilités PHP sont détectées ?", "options": ["SQLi, XSS, RCE, LFI, SSRF...", "SQLi seul", "XSS seul", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que RCE ?", "options": ["Remote Code Execution", "Remote Connection Error", "Resource Control", "Runtime Check"], "answer": 0},
            {"question": "Qu'est-ce que LFI ?", "options": ["Local File Inclusion", "Local File Injection", "Log File Include", "Link File"], "answer": 0},
            {"question": "Comment tree-sitter parse le PHP ?", "options": ["Génération d'AST (Abstract Syntax Tree)", "Regex", "String split", "Manual"], "answer": 0},
            {"question": "Qu'est-ce que l'AST ?", "options": ["Abstract Syntax Tree - représentation structurée du code", "Array String Table", "Analysis Structure", "Audit System"], "answer": 0},
            {"question": "Comment identifier un sink SQL ?", "options": ["Fonctions mysql_query, PDO::query, etc.", "echo", "print", "file_get"], "answer": 0},
            {"question": "Comment identifier un sink XSS ?", "options": ["echo, print, <?= sans échappement", "mysql_query", "include", "exec"], "answer": 0},
            {"question": "Qu'est-ce que SSRF ?", "options": ["Server-Side Request Forgery", "Server Security", "System Request", "Secure Service"], "answer": 0},
            {"question": "Comment détecter une injection de commande ?", "options": ["exec(), system(), shell_exec() avec input", "echo", "print", "include"], "answer": 0},
            {"question": "Comment gérer les faux positifs ?", "options": ["Whitelist, annotations, configuration", "Ignorer", "Supprimer", "Désactiver"], "answer": 0},
            {"question": "Qu'est-ce que le data flow analysis ?", "options": ["Suivre le flux de données dans le code", "Réseau", "Fichiers", "Mémoire"], "answer": 0},
            {"question": "Comment scanner un projet entier ?", "options": ["Récursif sur tous les fichiers PHP", "Un fichier", "Manuel", "Aléatoire"], "answer": 0},
            {"question": "Quel est l'avantage sur les scanners dynamiques ?", "options": ["Pas besoin d'exécuter le code", "Plus rapide", "Plus précis", "Plus simple"], "answer": 0},
            {"question": "Comment intégrer dans CI/CD ?", "options": ["Script dans pipeline, exit code sur erreurs", "Manuel", "Email", "Rapport"], "answer": 0},
            {"question": "Qu'est-ce que l'échappement de contexte ?", "options": ["htmlspecialchars, addslashes selon le contexte", "Suppression", "Chiffrement", "Compression"], "answer": 0},
            {"question": "Comment détecter les includes dangereux ?", "options": ["include/require avec variable non sanitisée", "include statique", "require_once", "use"], "answer": 0},
            {"question": "Qu'est-ce que l'object injection PHP ?", "options": ["Désérialisation non sécurisée", "Creation d'objet", "Instanciation", "Héritage"], "answer": 0},
            {"question": "Comment détecter l'object injection ?", "options": ["unserialize() avec input utilisateur", "new Object()", "clone", "extend"], "answer": 0},
            {"question": "Qu'est-ce que le path traversal ?", "options": ["Accès fichiers hors répertoire autorisé via ../", "Navigation web", "Routing", "Redirect"], "answer": 0},
            {"question": "Comment le scanner rapporte-t-il les résultats ?", "options": ["Ligne, fichier, type de vuln, sévérité", "Texte simple", "Nombre", "Booléen"], "answer": 0},
            {"question": "Quelle sévérité pour RCE ?", "options": ["Critical", "High", "Medium", "Low"], "answer": 0}
        ]
    }
}

# Ajouter les repos manquants avec des questions génériques
GENERIC_SECURITY_REPOS = {
    "Python.PiZero.WiFi": {
        "description": "Boîte à outils WiFi Raspberry Pi Zero",
        "questions": [
            {"question": "Quelle bibliothèque Python capture les paquets WiFi ?", "options": ["Scapy / pyshark", "requests", "socket", "urllib"], "answer": 0},
            {"question": "Qu'est-ce qu'une attaque de deauthentification ?", "options": ["Déconnecter un client WiFi de son AP", "Authentification forcée", "Connexion automatique", "Reset routeur"], "answer": 0},
            {"question": "Quel mode WiFi permet le sniffing ?", "options": ["Monitor mode", "Managed mode", "Ad-hoc", "Master"], "answer": 0},
            {"question": "Comment activer le mode monitor ?", "options": ["airmon-ng start wlan0", "ifconfig wlan0 monitor", "iwconfig mode monitor", "nmcli mon"], "answer": 0},
            {"question": "Qu'est-ce qu'un handshake WPA ?", "options": ["4-way handshake pour auth WiFi", "Connexion TCP", "SSL handshake", "DNS query"], "answer": 0},
            {"question": "Comment capturer un handshake ?", "options": ["Sniff pendant connexion ou forcer deauth", "Attendre", "Demander", "Scanner"], "answer": 0},
            {"question": "Quel framework web sert le dashboard ?", "options": ["Flask", "Django", "Node.js", "PHP"], "answer": 0},
            {"question": "Comment envoyer des alertes Telegram ?", "options": ["API Bot Telegram", "Email", "SMS", "Push"], "answer": 0},
            {"question": "Qu'est-ce que la géolocalisation WiFi ?", "options": ["Localiser via BSSID des APs", "GPS", "IP geolocation", "Cell towers"], "answer": 0},
            {"question": "Quelle base de données contient les positions WiFi ?", "options": ["Wigle, Google Location", "DNS", "WHOIS", "BGP"], "answer": 0},
            {"question": "Comment le Pi Zero se connecte-t-il au réseau ?", "options": ["USB gadget mode ou WiFi", "Ethernet", "Bluetooth seul", "Serial"], "answer": 0},
            {"question": "Quel chipset WiFi supporte le monitor mode ?", "options": ["Atheros, Realtek RTL8812AU", "Intel intégré", "Broadcom standard", "Tous"], "answer": 0},
            {"question": "Comment afficher les réseaux WiFi détectés ?", "options": ["Dashboard web temps réel", "Console", "Fichier", "Email"], "answer": 0},
            {"question": "Qu'est-ce qu'un Evil Twin ?", "options": ["Faux AP imitant un réseau légitime", "Connexion double", "Backup WiFi", "Mesh node"], "answer": 0},
            {"question": "Comment alimenter le Pi Zero sur le terrain ?", "options": ["Batterie USB / powerbank", "Secteur", "Solaire seul", "Pile"], "answer": 0},
            {"question": "Quel protocole le deauth utilise-t-il ?", "options": ["802.11 management frames", "TCP", "UDP", "ICMP"], "answer": 0},
            {"question": "Comment logger les probes requests ?", "options": ["Capturer et analyser les SSIDs recherchés", "Ping", "DNS", "ARP"], "answer": 0},
            {"question": "Qu'est-ce qu'une probe request ?", "options": ["Client cherchant des réseaux connus", "Connexion", "Déconnexion", "Auth"], "answer": 0},
            {"question": "Comment identifier les appareils par MAC ?", "options": ["OUI lookup fabricant", "DNS", "DHCP", "ARP"], "answer": 0},
            {"question": "Quel OS est recommandé pour le Pi ?", "options": ["Kali Linux / Raspbian", "Windows", "macOS", "BSD"], "answer": 0},
            {"question": "Comment sécuriser le dashboard ?", "options": ["Auth + HTTPS", "Rien", "Firewall seul", "VPN seul"], "answer": 0},
            {"question": "Qu'est-ce que pyshark ?", "options": ["Wrapper Python pour tshark", "Scanner", "Framework", "OS"], "answer": 0},
            {"question": "Comment stocker les données capturées ?", "options": ["SQLite, fichiers pcap", "Mémoire seule", "Cloud", "Email"], "answer": 0},
            {"question": "Qu'est-ce que le WPS ?", "options": ["WiFi Protected Setup - vulnérable", "Password System", "Protection WiFi", "Security Protocol"], "answer": 0},
            {"question": "Comment cracker un PIN WPS ?", "options": ["Reaver, Bully", "Bruteforce password", "Dictionary", "Social engineering"], "answer": 0},
            {"question": "Quel outil analyse les paquets capturés ?", "options": ["Wireshark, pyshark", "Nmap", "Netcat", "curl"], "answer": 0},
            {"question": "Comment détecter les clients connectés ?", "options": ["Analyse du trafic vers l'AP", "Ping broadcast", "DNS", "DHCP"], "answer": 0},
            {"question": "Qu'est-ce que le PMKID attack ?", "options": ["Crack WPA sans handshake complet", "Brute force", "Dictionary", "Rainbow"], "answer": 0},
            {"question": "Comment le dashboard affiche-t-il la map ?", "options": ["Leaflet / Google Maps avec positions", "Texte", "Liste", "Tableau"], "answer": 0},
            {"question": "Quel est l'objectif éducatif de ce projet ?", "options": ["Comprendre la sécurité WiFi", "Hacking", "Espionnage", "Rien"], "answer": 0}
        ]
    },
    "Python.QueryStringsFromPhp": {
        "description": "Extracteur de query strings depuis PHP",
        "questions": [
            {"question": "Qu'est-ce qu'une query string ?", "options": ["Paramètres dans l'URL après ?", "Corps de requête", "Header", "Cookie"], "answer": 0},
            {"question": "Quelles variables PHP contiennent les paramètres ?", "options": ["$_GET, $_POST, $_REQUEST", "$_SERVER", "$_SESSION", "$_ENV"], "answer": 0},
            {"question": "Comment extraire les paramètres d'un code PHP ?", "options": ["Parser et chercher $_GET['param']", "Regex simple", "Exécuter le code", "Deviner"], "answer": 0},
            {"question": "Quel est l'intérêt pour le pentesting ?", "options": ["Identifier les endpoints à tester", "Documentation", "Debugging", "Performance"], "answer": 0},
            {"question": "Comment parser du code PHP en Python ?", "options": ["tree-sitter ou php-parser", "Regex", "split()", "eval()"], "answer": 0},
            {"question": "Quel format de sortie est généré ?", "options": ["JSON avec liste des paramètres", "XML", "CSV", "Texte"], "answer": 0},
            {"question": "Comment scanner récursivement un projet ?", "options": ["os.walk() sur les fichiers .php", "Manuel", "Un fichier", "Aléatoire"], "answer": 0},
            {"question": "Qu'est-ce que l'AST PHP ?", "options": ["Abstract Syntax Tree du code", "Array String", "Analysis", "Audit"], "answer": 0},
            {"question": "Comment identifier $_POST['param'] ?", "options": ["Pattern matching dans l'AST", "Regex", "Recherche texte", "Grep"], "answer": 0},
            {"question": "Quels paramètres sont potentiellement vulnérables ?", "options": ["Ceux passés aux fonctions sensibles", "Tous", "Aucun", "Aléatoire"], "answer": 0},
            {"question": "Comment enrichir les résultats ?", "options": ["Ajouter le contexte d'utilisation", "Nom seul", "Type seul", "Rien"], "answer": 0},
            {"question": "Quel outil utilise ces résultats ?", "options": ["Scanners de vulnérabilités", "IDE", "Éditeur", "Navigateur"], "answer": 0},
            {"question": "Comment détecter filter_input() ?", "options": ["Chercher dans l'AST", "Regex", "Manuel", "Impossible"], "answer": 0},
            {"question": "Qu'est-ce que filter_input en PHP ?", "options": ["Fonction de validation d'entrée", "Filtre réseau", "Firewall", "Cache"], "answer": 0},
            {"question": "Comment différencier GET et POST ?", "options": ["$_GET vs $_POST dans le code", "Taille", "Type", "Extension"], "answer": 0},
            {"question": "Comment gérer les variables dynamiques ?", "options": ["$$var ou extract() sont complexes", "Simple", "Ignorer", "Erreur"], "answer": 0},
            {"question": "Quel est l'output attendu ?", "options": ["Liste de paramètres avec fichier/ligne", "Booléen", "Nombre", "HTML"], "answer": 0},
            {"question": "Comment intégrer avec sqlmap ?", "options": ["Fournir les paramètres à tester", "Direct", "Impossible", "Manuel"], "answer": 0},
            {"question": "Qu'est-ce que $_REQUEST ?", "options": ["Combine GET, POST, COOKIE", "GET seul", "POST seul", "COOKIE seul"], "answer": 0},
            {"question": "Comment gérer les frameworks PHP ?", "options": ["Patterns spécifiques (Laravel, Symfony)", "Universel", "Manuel", "Impossible"], "answer": 0},
            {"question": "Quel pattern Laravel utilise les paramètres ?", "options": ["$request->input()", "$_GET", "$_POST", "params()"], "answer": 0},
            {"question": "Comment exclure les faux positifs ?", "options": ["Vérifier le contexte d'utilisation", "Tout garder", "Tout supprimer", "Aléatoire"], "answer": 0},
            {"question": "Comment gérer les fichiers inclus ?", "options": ["Suivre les include/require", "Ignorer", "Erreur", "Manuel"], "answer": 0},
            {"question": "Quel est le workflow typique ?", "options": ["Extract -> Review -> Feed to scanner", "Direct scan", "Manuel", "Rien"], "answer": 0},
            {"question": "Comment détecter les paramètres de fichiers ?", "options": ["$_FILES dans le code", "$_GET", "$_POST", "$_REQUEST"], "answer": 0},
            {"question": "Qu'est-ce que $_SERVER ?", "options": ["Variables serveur et requête", "Paramètres GET", "Session", "Cookies"], "answer": 0},
            {"question": "Comment exporter vers un outil de scan ?", "options": ["JSON ou format compatible", "Manuel", "Copier-coller", "Email"], "answer": 0},
            {"question": "Quel paramètre $_SERVER est dangereux ?", "options": ["HTTP_HOST, REQUEST_URI si non validés", "DOCUMENT_ROOT", "PHP_SELF", "Tous"], "answer": 0},
            {"question": "Comment automatiser l'extraction ?", "options": ["Script en ligne de commande", "GUI", "Web", "API"], "answer": 0},
            {"question": "Quel est l'objectif final ?", "options": ["Alimenter les tests de sécurité", "Documentation", "Refactoring", "Performance"], "answer": 0}
        ]
    },
    "Python.Ransomware": {
        "description": "Étude des mécanismes de ransomware (éducatif)",
        "questions": [
            {"question": "Quel est l'objectif éducatif de ce repo ?", "options": ["Comprendre les ransomwares pour mieux se défendre", "Créer des malwares", "Attaquer", "Rien"], "answer": 0},
            {"question": "Quel algorithme de chiffrement les ransomwares utilisent ?", "options": ["AES + RSA hybride", "XOR simple", "Base64", "ROT13"], "answer": 0},
            {"question": "Pourquoi AES + RSA ensemble ?", "options": ["AES rapide pour données, RSA pour clé AES", "Compatibilité", "Standard", "Historique"], "answer": 0},
            {"question": "Comment le ransomware persiste-t-il ?", "options": ["Startup, registry, services", "Mémoire seule", "Temporaire", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que le C2 dans ce contexte ?", "options": ["Command and Control server", "Configuration", "Chiffrement", "Compression"], "answer": 0},
            {"question": "Comment la clé est-elle exfiltrée ?", "options": ["Envoyée au C2 avant chiffrement", "Stockée localement", "Email", "Pas exfiltrée"], "answer": 0},
            {"question": "Quelles extensions sont typiquement ciblées ?", "options": [".doc, .pdf, .jpg, .xls, bases de données", "Tout", ".exe seul", "Rien"], "answer": 0},
            {"question": "Comment se protéger contre les ransomwares ?", "options": ["Backups, patches, sensibilisation, EDR", "Antivirus seul", "Firewall seul", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que le shadow copy ?", "options": ["Backups Windows que les ransomwares suppriment", "Copie d'écran", "Backup cloud", "Archive"], "answer": 0},
            {"question": "Comment supprimer les shadow copies ?", "options": ["vssadmin delete shadows", "del shadows", "rm -rf", "format"], "answer": 0},
            {"question": "Qu'est-ce que la note de rançon ?", "options": ["Instructions de paiement", "Documentation", "Licence", "README"], "answer": 0},
            {"question": "Quel paiement est généralement demandé ?", "options": ["Cryptomonnaie (Bitcoin, Monero)", "Virement", "PayPal", "Cash"], "answer": 0},
            {"question": "Pourquoi la cryptomonnaie ?", "options": ["Anonymat relatif", "Rapidité", "Moins de frais", "Standard"], "answer": 0},
            {"question": "Qu'est-ce que le double extortion ?", "options": ["Chiffrement + menace de leak", "Double chiffrement", "Deux rançons", "Backup"], "answer": 0},
            {"question": "Comment un ransomware se propage-t-il ?", "options": ["Phishing, exploits, RDP, USB", "Email seul", "Web seul", "Réseau seul"], "answer": 0},
            {"question": "Qu'est-ce que le RaaS ?", "options": ["Ransomware as a Service", "Remote access", "Recovery", "Reporting"], "answer": 0},
            {"question": "Comment détecter un ransomware ?", "options": ["Comportement suspect, extensions modifiées, I/O élevé", "Antivirus seul", "Firewall", "Manuel"], "answer": 0},
            {"question": "Qu'est-ce que l'énumération de fichiers ?", "options": ["Parcourir le système pour trouver les cibles", "Listing", "Backup", "Recovery"], "answer": 0},
            {"question": "Comment éviter la détection sandbox ?", "options": ["Anti-VM checks, délais, user interaction", "Rien", "Obfuscation seule", "Chiffrement"], "answer": 0},
            {"question": "Qu'est-ce que le kill switch ?", "options": ["Mécanisme d'arrêt du malware", "Bouton physique", "Reset", "Shutdown"], "answer": 0},
            {"question": "Comment WannaCry a-t-il été stoppé ?", "options": ["Kill switch domain enregistré", "Patch", "Antivirus", "Firewall"], "answer": 0},
            {"question": "Qu'est-ce que la réponse à incident ?", "options": ["Procédure de gestion post-infection", "Prévention", "Detection", "Recovery"], "answer": 0},
            {"question": "Faut-il payer la rançon ?", "options": ["Non recommandé (pas de garantie, finance le crime)", "Toujours", "Parfois", "Dépend"], "answer": 0},
            {"question": "Qu'est-ce que No More Ransom ?", "options": ["Initiative avec décrypteurs gratuits", "Ransomware", "Outil", "Service"], "answer": 0},
            {"question": "Comment les backups protègent-ils ?", "options": ["Restauration sans payer", "Chiffrement", "Compression", "Rien"], "answer": 0},
            {"question": "Pourquoi les backups offline sont importants ?", "options": ["Non accessibles au ransomware", "Plus rapides", "Moins chers", "Standard"], "answer": 0},
            {"question": "Qu'est-ce que l'isolation réseau ?", "options": ["Segmenter pour limiter la propagation", "Déconnexion totale", "Firewall", "VPN"], "answer": 0},
            {"question": "Comment analyser un ransomware en sandbox ?", "options": ["Exécution dans VM isolée", "Production", "Réseau réel", "Hardware"], "answer": 0},
            {"question": "Qu'est-ce que YARA ?", "options": ["Règles de détection de malware", "Antivirus", "Firewall", "IDS"], "answer": 0},
            {"question": "Quel est le rôle de l'EDR ?", "options": ["Détection et réponse sur endpoints", "Antivirus", "Firewall", "Backup"], "answer": 0}
        ]
    },
    "Python.Session.Hijacking": {
        "description": "Démonstration de détournement de session HTTP",
        "questions": [
            {"question": "Qu'est-ce que le session hijacking ?", "options": ["Vol de session utilisateur pour usurpation", "Création de session", "Fermeture de session", "Reset"], "answer": 0},
            {"question": "Comment une session est-elle identifiée ?", "options": ["Cookie de session (PHPSESSID, etc.)", "IP", "User-Agent", "Referer"], "answer": 0},
            {"question": "Qu'est-ce que le rejeu de cookie ?", "options": ["Utiliser un cookie volé pour s'authentifier", "Créer un cookie", "Supprimer", "Modifier"], "answer": 0},
            {"question": "Comment voler un cookie de session ?", "options": ["XSS, sniffing, MITM", "Deviner", "Brute force", "Demander"], "answer": 0},
            {"question": "Quel attribut empêche le vol via XSS ?", "options": ["HttpOnly", "Secure", "SameSite", "Path"], "answer": 0},
            {"question": "Quel attribut protège en transit ?", "options": ["Secure (HTTPS only)", "HttpOnly", "SameSite", "Domain"], "answer": 0},
            {"question": "Qu'est-ce que le session fixation ?", "options": ["Forcer une session ID connue", "Voler la session", "Créer une session", "Fermer"], "answer": 0},
            {"question": "Comment se protéger du fixation ?", "options": ["Régénérer l'ID après login", "Cookies longs", "Timeouts courts", "HTTPS seul"], "answer": 0},
            {"question": "Qu'est-ce que le sniffing réseau ?", "options": ["Capture du trafic pour extraire les cookies", "Scan", "Ping", "Traceroute"], "answer": 0},
            {"question": "Pourquoi HTTPS est important ?", "options": ["Chiffre le trafic incluant les cookies", "Plus rapide", "Compatible", "Standard"], "answer": 0},
            {"question": "Comment démontrer le hijacking ?", "options": ["Intercepter et rejouer le cookie", "Théorie", "Documentation", "Rien"], "answer": 0},
            {"question": "Quel outil capture le trafic ?", "options": ["Wireshark, tcpdump", "Nmap", "Netcat", "curl"], "answer": 0},
            {"question": "Comment un attaquant sur le même réseau vole-t-il ?", "options": ["ARP spoofing + sniffing", "Brute force", "Deviner", "Demander"], "answer": 0},
            {"question": "Qu'est-ce que Firesheep ?", "options": ["Extension historique de hijacking WiFi", "Firewall", "Antivirus", "VPN"], "answer": 0},
            {"question": "Comment le serveur détecte-t-il le hijacking ?", "options": ["Changement IP/User-Agent, comportement anormal", "Toujours", "Jamais", "Parfois"], "answer": 0},
            {"question": "Qu'est-ce que le session binding ?", "options": ["Lier la session à des attributs client", "Créer une session", "Supprimer", "Modifier"], "answer": 0},
            {"question": "Comment lier une session à une IP ?", "options": ["Stocker et vérifier l'IP côté serveur", "Cookie", "Header", "Rien"], "answer": 0},
            {"question": "Pourquoi le binding IP pose problème ?", "options": ["IPs dynamiques, proxies, mobiles", "Sécurisé", "Standard", "Rapide"], "answer": 0},
            {"question": "Qu'est-ce que le token binding ?", "options": ["Lier le token à la clé TLS du client", "Cookie", "Session", "Header"], "answer": 0},
            {"question": "Comment les timeouts aident-ils ?", "options": ["Limiter la fenêtre d'exploitation", "Performance", "UX", "Standard"], "answer": 0},
            {"question": "Quelle durée de session est recommandée ?", "options": ["Selon le risque (banque: court, news: long)", "Infinie", "1 minute", "1 an"], "answer": 0},
            {"question": "Comment forcer la déconnexion ?", "options": ["Invalider la session côté serveur", "Supprimer cookie", "Fermer navigateur", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que le logout sécurisé ?", "options": ["Invalider serveur + supprimer cookie", "Supprimer cookie seul", "Redirection", "Rien"], "answer": 0},
            {"question": "Comment les frameworks gèrent-ils les sessions ?", "options": ["Mécanismes intégrés sécurisés", "Manuel", "Rien", "Cookie simple"], "answer": 0},
            {"question": "Qu'est-ce que JWT pour les sessions ?", "options": ["Token signé côté client", "Cookie classique", "Session serveur", "Header simple"], "answer": 0},
            {"question": "Quels risques avec JWT ?", "options": ["Vol du token = accès complet", "Aucun", "Performance", "Compatibilité"], "answer": 0},
            {"question": "Comment stocker JWT de manière sécurisée ?", "options": ["Cookie HttpOnly vs localStorage (débat)", "Texte clair", "URL", "Header"], "answer": 0},
            {"question": "Qu'est-ce que le refresh token ?", "options": ["Token longue durée pour renouveler l'access token", "Session", "Cookie", "Header"], "answer": 0},
            {"question": "Comment détecter le vol de refresh token ?", "options": ["Rotation et détection de réutilisation", "Rien", "Logs", "Alerte"], "answer": 0},
            {"question": "Qu'est-ce que la révocation de token ?", "options": ["Invalider un token avant expiration", "Supprimer", "Renouveler", "Créer"], "answer": 0}
        ]
    },
    "Python.Traversal.Vulnerabilities": {
        "description": "Scanner de vulnérabilités path traversal",
        "questions": [
            {"question": "Qu'est-ce que le path traversal ?", "options": ["Accès à des fichiers hors du répertoire autorisé", "Navigation web", "Routing", "Redirection"], "answer": 0},
            {"question": "Quelle séquence est utilisée pour remonter ?", "options": ["../", "..\\\\", "%2e%2e/", "Toutes"], "answer": 3},
            {"question": "Comment encoder ../ pour contourner les filtres ?", "options": ["%2e%2e%2f, ..%252f, ....//", "Base64", "Hex", "ROT13"], "answer": 0},
            {"question": "Quel fichier Unix est souvent ciblé ?", "options": ["/etc/passwd", "/etc/hosts", "/etc/resolv.conf", "/var/log"], "answer": 0},
            {"question": "Quel fichier Windows est ciblé ?", "options": ["C:\\\\Windows\\\\win.ini", "C:\\\\boot.ini", "C:\\\\config.sys", "Tous"], "answer": 0},
            {"question": "Comment tester automatiquement ?", "options": ["Injecter des payloads traversal dans les paramètres", "Manuel", "Deviner", "Rien"], "answer": 0},
            {"question": "Quel paramètre est souvent vulnérable ?", "options": ["file=, path=, document=, page=", "id=", "name=", "user="], "answer": 0},
            {"question": "Comment valider une vulnérabilité ?", "options": ["Contenu du fichier dans la réponse", "Status 200", "Redirection", "Timeout"], "answer": 0},
            {"question": "Qu'est-ce que le null byte injection ?", "options": ["%00 pour tronquer l'extension", "Byte vide", "Caractère spécial", "Encodage"], "answer": 0},
            {"question": "Pourquoi %00 fonctionne-t-il ?", "options": ["Langages C-based terminent les strings au null", "Standard", "Bug", "Feature"], "answer": 0},
            {"question": "Comment le serveur devrait-il valider ?", "options": ["Whitelist, canonicalisation, chroot", "Blacklist seule", "Rien", "Regex simple"], "answer": 0},
            {"question": "Qu'est-ce que la canonicalisation ?", "options": ["Résoudre le chemin réel avant validation", "Encodage", "Compression", "Chiffrement"], "answer": 0},
            {"question": "Comment PHP résout-il les chemins ?", "options": ["realpath()", "resolve()", "canonicalize()", "normalize()"], "answer": 0},
            {"question": "Quel impact peut avoir le path traversal ?", "options": ["Lecture fichiers sensibles, parfois RCE", "Rien", "DoS seul", "Lenteur"], "answer": 0},
            {"question": "Comment combiner avec LFI ?", "options": ["Inclure un fichier après traversal", "Séparément", "Impossible", "Manuel"], "answer": 0},
            {"question": "Qu'est-ce que le wrapper PHP ?", "options": ["php://filter, data://, expect://", "Extension", "Module", "Framework"], "answer": 0},
            {"question": "Comment php://filter aide l'attaque ?", "options": ["Lire le code source en base64", "Exécuter", "Supprimer", "Modifier"], "answer": 0},
            {"question": "Quel payload lit le code PHP ?", "options": ["php://filter/convert.base64-encode/resource=", "file://", "http://", "ftp://"], "answer": 0},
            {"question": "Comment tester les séquences doubles ?", "options": ["....// si le serveur filtre ../ une fois", "../", "....\\\\", ".../"], "answer": 0},
            {"question": "Qu'est-ce que le directory indexing ?", "options": ["Liste des fichiers si pas d'index", "Traversal", "LFI", "RFI"], "answer": 0},
            {"question": "Comment combiner avec upload ?", "options": ["Uploader puis inclure via traversal", "Séparément", "Impossible", "Direct"], "answer": 0},
            {"question": "Quel outil automatise ces tests ?", "options": ["Burp Suite, ffuf, custom scripts", "Nmap", "Wireshark", "tcpdump"], "answer": 0},
            {"question": "Comment générer les payloads ?", "options": ["Wordlists + encodages multiples", "Manuel", "Aléatoire", "Fixe"], "answer": 0},
            {"question": "Qu'est-ce que le dot-dot-slash filtering ?", "options": ["Serveur supprimant ../", "Encodage", "Validation", "Chiffrement"], "answer": 0},
            {"question": "Comment contourner le filtering ?", "options": ["Encodage, double-encoding, null bytes", "Impossible", "Brute force", "Demander"], "answer": 0},
            {"question": "Quel framework a eu des vulnérabilités connues ?", "options": ["Tous ont eu des cas", "Aucun", "PHP seul", "Java seul"], "answer": 0},
            {"question": "Comment le WAF détecte-t-il ?", "options": ["Patterns ../, encodages suspects", "Taille", "Méthode", "Header"], "answer": 0},
            {"question": "Comment contourner le WAF ?", "options": ["Encodages alternatifs, double-encoding", "Direct", "Impossible", "Demander"], "answer": 0},
            {"question": "Quel est le risque maximal ?", "options": ["RCE via log poisoning + LFI", "Lecture seule", "DoS", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que le log poisoning ?", "options": ["Injecter du code dans les logs puis inclure", "Supprimer logs", "Lire logs", "Modifier logs"], "answer": 0}
        ]
    },
    "Python.Usb.Test": {
        "description": "Test de sécurité USB",
        "questions": [
            {"question": "Qu'est-ce qu'un BadUSB ?", "options": ["USB malveillant émulant clavier/souris", "USB défectueux", "Stockage lent", "Hub USB"], "answer": 0},
            {"question": "Quel danger pose un USB inconnu ?", "options": ["Injection de commandes, malware, exfiltration", "Aucun", "Lenteur", "Incompatibilité"], "answer": 0},
            {"question": "Comment détecter un nouveau périphérique USB ?", "options": ["udev, pyudev, polling", "Manuel", "Antivirus", "Firewall"], "answer": 0},
            {"question": "Qu'est-ce que udev ?", "options": ["Gestionnaire de périphériques Linux", "Firewall", "Antivirus", "Service"], "answer": 0},
            {"question": "Comment logger les connexions USB ?", "options": ["Hook udev + logging", "Manuel", "Fichier", "Email"], "answer": 0},
            {"question": "Qu'est-ce que le HID (Human Interface Device) ?", "options": ["Classe USB pour claviers/souris", "Stockage", "Audio", "Vidéo"], "answer": 0},
            {"question": "Pourquoi HID est-il dangereux ?", "options": ["Exécution automatique de frappes", "Lent", "Gros", "Bruyant"], "answer": 0},
            {"question": "Qu'est-ce que Rubber Ducky ?", "options": ["Outil d'injection de frappes via USB", "Canard", "Jouet", "Stockage"], "answer": 0},
            {"question": "Comment analyser le comportement USB ?", "options": ["Surveiller les descripteurs et trafic", "Démonter", "Scanner", "Ping"], "answer": 0},
            {"question": "Qu'est-ce qu'un descripteur USB ?", "options": ["Métadonnées décrivant le périphérique", "Driver", "Firmware", "Software"], "answer": 0},
            {"question": "Comment un USB peut-il être un clavier ET stockage ?", "options": ["Descripteurs multiples (composite device)", "Impossible", "Driver spécial", "Firmware"], "answer": 0},
            {"question": "Comment bloquer les USB non autorisés ?", "options": ["Whitelist par VID/PID, USBGuard", "Firewall", "Antivirus", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que VID/PID ?", "options": ["Vendor ID / Product ID", "Version", "Protocol", "Driver"], "answer": 0},
            {"question": "Comment USBGuard fonctionne-t-il ?", "options": ["Politique d'autorisation des USB", "Antivirus", "Firewall", "IDS"], "answer": 0},
            {"question": "Qu'est-ce que l'USB Killer ?", "options": ["USB qui détruit physiquement le port", "Malware", "BadUSB", "Stockage"], "answer": 0},
            {"question": "Comment se protéger de l'USB Killer ?", "options": ["Protection électrique, ne pas brancher d'inconnus", "Antivirus", "Firewall", "Rien"], "answer": 0},
            {"question": "Comment analyser un USB suspect ?", "options": ["Machine isolée / VM avec USB passthrough", "Production", "Réseau", "Cloud"], "answer": 0},
            {"question": "Qu'est-ce que le USB mass storage ?", "options": ["Classe USB pour stockage", "HID", "Audio", "Video"], "answer": 0},
            {"question": "Comment empêcher l'autorun ?", "options": ["Désactiver autorun/autoplay", "Firewall", "Antivirus", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que l'exfiltration USB ?", "options": ["Vol de données via USB", "Import", "Backup", "Sync"], "answer": 0},
            {"question": "Comment détecter l'exfiltration ?", "options": ["DLP, monitoring des accès fichiers", "Firewall", "Antivirus", "Rien"], "answer": 0},
            {"question": "Qu'est-ce qu'un USB data blocker ?", "options": ["Adaptateur bloquant les data pins", "Câble", "Hub", "Switch"], "answer": 0},
            {"question": "Comment fonctionne un data blocker ?", "options": ["Ne connecte que l'alimentation", "Bloque tout", "Filtre", "Chiffre"], "answer": 0},
            {"question": "Qu'est-ce que le USB restricted mode (iOS) ?", "options": ["Bloquer le data après verrouillage", "Mode avion", "Économie batterie", "Silencieux"], "answer": 0},
            {"question": "Comment tester la sécurité USB d'un système ?", "options": ["Brancher des USB avec payloads de test", "Théorie", "Documentation", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que pyusb ?", "options": ["Bibliothèque Python pour USB", "Framework", "OS", "Service"], "answer": 0},
            {"question": "Comment lister les périphériques USB ?", "options": ["usb.core.find() avec pyusb", "ls -la", "cat /dev", "lsusb seul"], "answer": 0},
            {"question": "Comment identifier un USB malveillant ?", "options": ["Comportement anormal, multiple interfaces", "Apparence", "Marque", "Taille"], "answer": 0},
            {"question": "Qu'est-ce que le USB debugging (Android) ?", "options": ["ADB access via USB", "Mode développeur", "Root", "Jailbreak"], "answer": 0},
            {"question": "Pourquoi désactiver USB debugging en prod ?", "options": ["Accès complet au device", "Lenteur", "Batterie", "Espace"], "answer": 0}
        ]
    },
    "Raspberry.Hack": {
        "description": "Test de sécurité embarquée sur Raspberry Pi",
        "questions": [
            {"question": "Pourquoi le Raspberry Pi pour le hacking ?", "options": ["Petit, silencieux, low-cost, Linux complet", "Puissant", "Cher", "Bruyant"], "answer": 0},
            {"question": "Quelle distribution est recommandée ?", "options": ["Kali Linux ARM ou P4wnP1", "Windows", "macOS", "Android"], "answer": 0},
            {"question": "Qu'est-ce que P4wnP1 ?", "options": ["Plateforme d'attaque USB sur Pi Zero", "Distribution", "Outil", "Service"], "answer": 0},
            {"question": "Comment le Pi peut-il être une drop box ?", "options": ["Laisser sur le réseau cible pour accès distant", "Router", "Switch", "Hub"], "answer": 0},
            {"question": "Qu'est-ce qu'une drop box en pentest ?", "options": ["Device laissé pour maintenir l'accès", "Boîte aux lettres", "Stockage", "Backup"], "answer": 0},
            {"question": "Comment alimenter le Pi discrètement ?", "options": ["Power over Ethernet, batterie, USB mural", "Solaire seul", "Éolien", "Manuel"], "answer": 0},
            {"question": "Qu'est-ce que le wardriving sur Pi ?", "options": ["Scanner les WiFi en mouvement", "Conduire", "Navigation", "GPS"], "answer": 0},
            {"question": "Quels accessoires sont utiles ?", "options": ["Antenne WiFi, GPS, batterie, écran", "Rien", "Clavier seul", "Souris seule"], "answer": 0},
            {"question": "Comment le Pi Zero fonctionne en USB gadget ?", "options": ["Émule des périphériques USB", "Stockage seul", "Rien", "Impossible"], "answer": 0},
            {"question": "Qu'est-ce que le USB gadget mode ?", "options": ["Pi agit comme périphérique USB", "Host USB", "Hub", "Storage"], "answer": 0},
            {"question": "Comment établir une connexion reverse shell ?", "options": ["Script au boot + tunnel vers serveur", "Manuel", "Email", "SMS"], "answer": 0},
            {"question": "Comment sécuriser le Pi contre la capture ?", "options": ["Chiffrement disque, auto-destruct", "Rien", "Password seul", "PIN"], "answer": 0},
            {"question": "Qu'est-ce que LUKS ?", "options": ["Linux Unified Key Setup - chiffrement disque", "Antivirus", "Firewall", "IDS"], "answer": 0},
            {"question": "Comment le Pi peut scanner le réseau ?", "options": ["Nmap, Masscan, scripts Python", "Ping seul", "Manuel", "Rien"], "answer": 0},
            {"question": "Comment exfiltrer les données ?", "options": ["DNS tunnel, ICMP, HTTPS, cellular", "USB seul", "Email seul", "Rien"], "answer": 0},
            {"question": "Qu'est-ce qu'un implant hardware ?", "options": ["Device malveillant placé physiquement", "Malware", "Virus", "Trojan"], "answer": 0},
            {"question": "Comment détecter un Pi non autorisé ?", "options": ["Inventaire réseau, NAC, inspection physique", "Antivirus", "Firewall seul", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que le NAC ?", "options": ["Network Access Control", "Antivirus", "Firewall", "IDS"], "answer": 0},
            {"question": "Comment le Pi peut intercepter le trafic ?", "options": ["ARP spoofing, bridge mode", "Passif seul", "DNS", "DHCP"], "answer": 0},
            {"question": "Comment persister sur le réseau ?", "options": ["Services au boot, cron, SSH keys", "Manuel", "Temporaire", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que le red teaming avec Pi ?", "options": ["Simulation d'attaque réaliste", "Blue team", "Purple team", "Rien"], "answer": 0},
            {"question": "Comment camoufler le Pi ?", "options": ["Boîtier neutre, câblage propre", "Stickers", "Peinture", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que le physical pentest ?", "options": ["Test de sécurité physique", "Pentest web", "Pentest app", "Audit"], "answer": 0},
            {"question": "Comment le Pi aide en physical pentest ?", "options": ["Drop box, clone badge, WiFi attack", "Théorie", "Documentation", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que Proxmark ?", "options": ["Outil de clone RFID/NFC", "Scanner", "Router", "Switch"], "answer": 0},
            {"question": "Comment combiner Pi + Proxmark ?", "options": ["Automatisation des attaques badge", "Stockage", "Réseau", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que le HackRF ?", "options": ["Software Defined Radio pour RF attacks", "WiFi", "Bluetooth", "USB"], "answer": 0},
            {"question": "Comment le Pi gère les logs ?", "options": ["rsyslog, rotation, envoi distant", "Rien", "Local seul", "Mémoire"], "answer": 0},
            {"question": "Qu'est-ce que l'attestation de device ?", "options": ["Vérifier l'intégrité du système", "Login", "Logout", "Reset"], "answer": 0},
            {"question": "Comment détruire les preuves sur le Pi ?", "options": ["Wipe sécurisé, auto-destruct", "Format normal", "Delete", "Rien"], "answer": 0}
        ]
    },
    "Raspberry.IpBlocker": {
        "description": "Blocage automatique d'IP malveillantes",
        "questions": [
            {"question": "Quel outil Linux gère le firewall ?", "options": ["iptables / nftables", "firewalld seul", "ufw seul", "Rien"], "answer": 0},
            {"question": "Comment bloquer une IP avec iptables ?", "options": ["iptables -A INPUT -s IP -j DROP", "iptables block IP", "iptables deny IP", "iptables reject IP"], "answer": 0},
            {"question": "Qu'est-ce que fail2ban ?", "options": ["Outil de blocage automatique sur patterns de logs", "Firewall", "IDS", "Antivirus"], "answer": 0},
            {"question": "Comment fail2ban détecte les attaques ?", "options": ["Regex sur fichiers de logs", "Réseau", "Mémoire", "CPU"], "answer": 0},
            {"question": "Qu'est-ce qu'un jail dans fail2ban ?", "options": ["Configuration pour un service spécifique", "Prison", "Container", "VM"], "answer": 0},
            {"question": "Comment configurer un jail ?", "options": ["/etc/fail2ban/jail.local", "/etc/fail2ban.conf", "~/.fail2ban", "/var/fail2ban"], "answer": 0},
            {"question": "Qu'est-ce que le ban time ?", "options": ["Durée du blocage", "Temps de détection", "Latence", "Timeout"], "answer": 0},
            {"question": "Qu'est-ce que le find time ?", "options": ["Fenêtre de temps pour compter les échecs", "Ban time", "Max retry", "Timeout"], "answer": 0},
            {"question": "Qu'est-ce que max retry ?", "options": ["Nombre d'échecs avant ban", "Essais totaux", "Connexions max", "Timeout"], "answer": 0},
            {"question": "Comment lister les IPs bannies ?", "options": ["fail2ban-client status jail_name", "iptables -L", "cat /var/log/ban", "fail2ban list"], "answer": 0},
            {"question": "Comment débannir une IP ?", "options": ["fail2ban-client unban IP", "iptables -D", "fail2ban unban", "unblock IP"], "answer": 0},
            {"question": "Quelles sources d'IP malveillantes existent ?", "options": ["AbuseIPDB, Shodan, threat feeds", "Google", "Bing", "Yahoo"], "answer": 0},
            {"question": "Comment automatiser le blocage depuis feeds ?", "options": ["Script + cron + iptables/ipset", "Manuel", "Email", "SMS"], "answer": 0},
            {"question": "Qu'est-ce que ipset ?", "options": ["Structure efficace pour gérer des listes d'IPs", "iptables", "firewall", "IDS"], "answer": 0},
            {"question": "Pourquoi ipset vs règles iptables multiples ?", "options": ["Performance (O(1) lookup)", "Simplicité", "Compatibilité", "Standard"], "answer": 0},
            {"question": "Comment créer un ipset ?", "options": ["ipset create blacklist hash:ip", "ipset new", "ipset add", "ipset init"], "answer": 0},
            {"question": "Comment ajouter une IP à ipset ?", "options": ["ipset add blacklist IP", "ipset insert", "ipset append", "ipset push"], "answer": 0},
            {"question": "Comment utiliser ipset avec iptables ?", "options": ["iptables -m set --match-set blacklist src -j DROP", "iptables -j ipset", "iptables --ipset", "iptables -s ipset"], "answer": 0},
            {"question": "Comment géolocaliser les IPs bloquées ?", "options": ["GeoIP database", "DNS", "WHOIS", "Ping"], "answer": 0},
            {"question": "Comment logger les tentatives bloquées ?", "options": ["iptables -j LOG avant DROP", "Après DROP", "Pas possible", "Automatique"], "answer": 0},
            {"question": "Qu'est-ce que le rate limiting ?", "options": ["Limiter les connexions par temps", "Blocage total", "Whitelist", "Blacklist"], "answer": 0},
            {"question": "Comment implémenter le rate limiting ?", "options": ["iptables -m limit ou hashlimit", "Fail2ban", "ipset", "Script"], "answer": 0},
            {"question": "Comment persister les règles iptables ?", "options": ["iptables-save / iptables-persistent", "Automatique", "Fichier", "Database"], "answer": 0},
            {"question": "Comment tester le blocage ?", "options": ["Connexion depuis IP bloquée", "Ping", "Traceroute", "DNS"], "answer": 0},
            {"question": "Qu'est-ce que le tarpit ?", "options": ["Ralentir les connexions au lieu de bloquer", "Bloquer", "Rediriger", "Logger"], "answer": 0},
            {"question": "Comment alerter sur les blocages ?", "options": ["Email, Slack, webhook, SIEM", "Rien", "Log seul", "Console"], "answer": 0},
            {"question": "Comment whitelister certaines IPs ?", "options": ["Règle ACCEPT avant les règles de blocage", "Après", "Séparément", "ipset whitelist"], "answer": 0},
            {"question": "Qu'est-ce qu'un honeypot dans ce contexte ?", "options": ["Faux service pour attirer et identifier les attaquants", "Piège", "Leurre", "Tous"], "answer": 3},
            {"question": "Comment intégrer avec un SIEM ?", "options": ["Envoyer les logs de blocage en syslog", "Email", "SMS", "Rien"], "answer": 0},
            {"question": "Comment gérer les faux positifs ?", "options": ["Review des logs, whitelist, ajustement seuils", "Ignorer", "Tout bloquer", "Rien"], "answer": 0}
        ]
    },
    "typescript.PHP.Sec.Scan": {
        "description": "Extension VS Code pour sécurité PHP",
        "questions": [
            {"question": "Quel IDE cette extension cible ?", "options": ["VS Code", "IntelliJ", "Eclipse", "Sublime"], "answer": 0},
            {"question": "Quel langage est utilisé pour l'extension ?", "options": ["TypeScript", "JavaScript", "Python", "Java"], "answer": 0},
            {"question": "Qu'est-ce que le taint tracking temps réel ?", "options": ["Détection pendant l'écriture du code", "Après commit", "Build seul", "Deploy"], "answer": 0},
            {"question": "Comment l'extension affiche les vulnérabilités ?", "options": ["Diagnostics inline (underline, problems panel)", "Console", "Fichier", "Email"], "answer": 0},
            {"question": "Qu'est-ce que le Language Server Protocol ?", "options": ["Standard de communication éditeur-serveur d'analyse", "Protocole réseau", "API", "Framework"], "answer": 0},
            {"question": "Comment l'extension parse le PHP ?", "options": ["tree-sitter ou php-parser WASM", "Regex", "String", "Eval"], "answer": 0},
            {"question": "Qu'est-ce que WASM ?", "options": ["WebAssembly - code compilé dans le navigateur/Node", "Framework", "Langage", "API"], "answer": 0},
            {"question": "Comment configurer les règles ?", "options": ["settings.json ou fichier de config", "Code", "Registry", "Cloud"], "answer": 0},
            {"question": "Quels types de vulnérabilités sont détectées ?", "options": ["SQLi, XSS, RCE, LFI, etc.", "Typos seuls", "Format", "Rien"], "answer": 0},
            {"question": "Comment l'extension gère les frameworks ?", "options": ["Règles spécifiques Laravel, Symfony, etc.", "Universel", "Manuel", "Pas de support"], "answer": 0},
            {"question": "Qu'est-ce qu'un diagnostic VS Code ?", "options": ["Warning/error affiché dans l'éditeur", "Log", "Console", "Terminal"], "answer": 0},
            {"question": "Comment ignorer un faux positif ?", "options": ["Commentaire spécial ou configuration", "Supprimer le code", "Ignorer", "Rien"], "answer": 0},
            {"question": "Qu'est-ce qu'un code action ?", "options": ["Suggestion de fix (quick fix)", "Refactoring", "Format", "Save"], "answer": 0},
            {"question": "Comment l'extension suggère des corrections ?", "options": ["Code actions avec suggestions de fix", "Manuel", "Documentation", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que le hover information ?", "options": ["Info affichée au survol du code", "Tooltip", "Popup", "Dialog"], "answer": 0},
            {"question": "Comment voir les détails d'une vulnérabilité ?", "options": ["Hover sur le code souligné", "Click", "Menu", "Shortcut"], "answer": 0},
            {"question": "Comment l'extension s'active ?", "options": ["Automatiquement sur fichiers PHP", "Manuel", "Commande", "Settings"], "answer": 0},
            {"question": "Qu'est-ce que l'activation event ?", "options": ["Événement déclenchant l'extension", "User action", "Build", "Save"], "answer": 0},
            {"question": "Comment publier une extension VS Code ?", "options": ["Marketplace via vsce publish", "GitHub", "npm", "Manual"], "answer": 0},
            {"question": "Qu'est-ce que vsce ?", "options": ["Visual Studio Code Extension CLI", "Compiler", "Builder", "Packager"], "answer": 0},
            {"question": "Comment debugger l'extension ?", "options": ["F5 dans VS Code (Extension Development Host)", "Console", "Logs", "Print"], "answer": 0},
            {"question": "Qu'est-ce que le Extension Development Host ?", "options": ["Instance VS Code pour tester l'extension", "Server", "Container", "VM"], "answer": 0},
            {"question": "Comment tester l'extension ?", "options": ["Mocha / Jest avec vscode-test", "Manuel", "Prod", "Staging"], "answer": 0},
            {"question": "Qu'est-ce que le contribution point ?", "options": ["Fonctionnalité ajoutée à VS Code", "API", "Event", "Command"], "answer": 0},
            {"question": "Comment ajouter une commande ?", "options": ["contributes.commands dans package.json", "Code seul", "API", "Event"], "answer": 0},
            {"question": "Qu'est-ce que le webview ?", "options": ["Panel HTML personnalisé dans VS Code", "Browser", "Tab", "Window"], "answer": 0},
            {"question": "Comment afficher un rapport détaillé ?", "options": ["Webview avec HTML/CSS/JS", "Console", "Terminal", "Output"], "answer": 0},
            {"question": "Comment l'extension gère la performance ?", "options": ["Analyse incrémentale, debounce", "Tout recalculer", "Cache seul", "Rien"], "answer": 0},
            {"question": "Qu'est-ce que le debounce ?", "options": ["Attendre avant de re-analyser après modification", "Throttle", "Delay", "Wait"], "answer": 0},
            {"question": "Comment intégrer avec CI/CD ?", "options": ["CLI companion ou version Python/Node séparée", "Extension seule", "Impossible", "Manuel"], "answer": 0}
        ]
    }
}

REMAINING_QCM.update(GENERIC_SECURITY_REPOS)

QCM_HTML_TEMPLATE = '''---
layout: qcm
title: "QCM - {repo_name}"
repo_name: "{repo_name}"
description: "{description}"
readme_url: "../"
generated_at: "{timestamp}"
questions: {questions_json}
---
'''

def generate_remaining_qcm():
    for repo_name, data in REMAINING_QCM.items():
        repo_dir = os.path.join(REPOS_DIR, repo_name, "qcm")
        os.makedirs(repo_dir, exist_ok=True)

        qcm_file = os.path.join(repo_dir, "index.html")
        questions_json = json.dumps(data["questions"], ensure_ascii=False, indent=2)

        content = QCM_HTML_TEMPLATE.format(
            repo_name=repo_name,
            description=data["description"],
            timestamp=TIMESTAMP,
            questions_json=questions_json
        )

        with open(qcm_file, 'w', encoding='utf-8') as f:
            f.write(content)

        print(f"✓ QCM généré: {repo_name}")

    print(f"\n=== {len(REMAINING_QCM)} QCM supplémentaires générés ===")

if __name__ == "__main__":
    generate_remaining_qcm()
